name: Create and publish a Docker image

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate custom Docker tag part
        id: custom_tag # Give the step an ID to reference its outputs
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          # Basic sanitization for branch name (replace / with -) if needed for complex branch names
          # BRANCH_NAME=$(echo "${BRANCH_NAME}" | sed 's/\//-/g')
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7) # Get first 7 chars of the SHA
          TIMESTAMP=$(date +%s) # Get current Unix timestamp
          # Output the tag part (without image name)
          echo "tag_part=${BRANCH_NAME}-${SHORT_SHA}-${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Add 'latest' tag if on the main branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }} # Only push on actual push events, not PRs (safety check)
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.custom_tag.outputs.tag_part }}
          labels: ${{ steps.meta.outputs.labels }}
